services:
  service1:
    build:
      context: ./service1
    ports:
      - "8081:8081"
    networks:
      - webnet

  service2:
    build:
      context: ./service2
    ports:
      - "3000:3000"
    networks:
      - webnet

  service3:
    build:
      context: ./service3
    ports:
      - "8080:8080"
    networks:
      - webnet

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
      - service3
    networks:
      - webnet

networks:
  webnet:
